
    drop table Hop if exists

    drop table Malt if exists

    drop table Recipe if exists

    create table Hop (
        id bigint generated by default as identity (start with 1),
        version bigint,
        description varchar(255),
        name varchar(255),
        primary key (id),
        unique (name)
    )

    create table Malt (
        id bigint generated by default as identity (start with 1),
        version bigint,
        description varchar(255),
        name varchar(255),
        primary key (id),
        unique (name)
    )

    create table Recipe (
        id bigint generated by default as identity (start with 1),
        version bigint,
        description varchar(255),
        name varchar(255),
        primary key (id),
        unique (name)
    )
