
    alter table MaltAddition 
        drop constraint FKB3D29D58506F9AA6

    alter table Mash 
        drop constraint FK247B09D24AAA90

    alter table Mash_MashStep 
        drop constraint FKE1C559EBB55B5164

    alter table Mash_MashStep 
        drop constraint FKE1C559EB429CDDD2

    alter table Recipe 
        drop constraint FK91AB41AEB55B5164

    alter table Recipe_MaltAddition 
        drop constraint FKC7977049D9FA8C4

    alter table Recipe_MaltAddition 
        drop constraint FKC797704946F16405

    drop table Hop if exists

    drop table Malt if exists

    drop table MaltAddition if exists

    drop table Mash if exists

    drop table MashStep if exists

    drop table MashTun if exists

    drop table Mash_MashStep if exists

    drop table Recipe if exists

    drop table Recipe_MaltAddition if exists

    create table Hop (
        id bigint generated by default as identity (start with 1),
        version bigint,
        description clob,
        name varchar(255),
        primary key (id),
        unique (name)
    )

    create table Malt (
        id bigint generated by default as identity (start with 1),
        version bigint,
        description varchar(255),
        name varchar(255),
        primary key (id),
        unique (name)
    )

    create table MaltAddition (
        id bigint generated by default as identity (start with 1),
        version bigint,
        weight double,
        type_id bigint,
        primary key (id)
    )

    create table Mash (
        id bigint generated by default as identity (start with 1),
        version bigint,
        thickness double,
        mashTun_id bigint,
        primary key (id)
    )

    create table MashStep (
        id bigint generated by default as identity (start with 1),
        version bigint,
        temperature double,
        volume double,
        initialTemperature double,
        order integer not null,
        recordedTemperature double,
        targetTemperature double,
        primary key (id)
    )

    create table MashTun (
        id bigint generated by default as identity (start with 1),
        version bigint,
        thermalMass double,
        primary key (id)
    )

    create table Mash_MashStep (
        Mash_id bigint not null,
        steps_id bigint not null,
        order integer not null,
        primary key (Mash_id, order),
        unique (steps_id)
    )

    create table Recipe (
        id bigint generated by default as identity (start with 1),
        version bigint,
        description varchar(255),
        name varchar(255),
        mash_id bigint,
        primary key (id),
        unique (name)
    )

    create table Recipe_MaltAddition (
        Recipe_id bigint not null,
        malts_id bigint not null,
        unique (malts_id)
    )

    alter table MaltAddition 
        add constraint FKB3D29D58506F9AA6 
        foreign key (type_id) 
        references Malt

    alter table Mash 
        add constraint FK247B09D24AAA90 
        foreign key (mashTun_id) 
        references MashTun

    alter table Mash_MashStep 
        add constraint FKE1C559EBB55B5164 
        foreign key (Mash_id) 
        references Mash

    alter table Mash_MashStep 
        add constraint FKE1C559EB429CDDD2 
        foreign key (steps_id) 
        references MashStep

    alter table Recipe 
        add constraint FK91AB41AEB55B5164 
        foreign key (mash_id) 
        references Mash

    alter table Recipe_MaltAddition 
        add constraint FKC7977049D9FA8C4 
        foreign key (Recipe_id) 
        references Recipe

    alter table Recipe_MaltAddition 
        add constraint FKC797704946F16405 
        foreign key (malts_id) 
        references MaltAddition
